import type { Metadata } from "next";
import AppWalletProvider from "./components/AppWalletProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
        		<AppWalletProvider>
          			{children}
 				</AppWalletProvider>
			</body>
    	</html>
  	);
}
